CREATE TABLE person (
    -- O tipo 'BIGINT' é usado. O '(28)' do seu exemplo não é aplicável no PostgreSQL,
    -- pois BIGINT tem um tamanho fixo.
    -- 'GENERATED BY DEFAULT AS IDENTITY' é a forma moderna e padrão SQL para autoincremento.
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

                        first_name VARCHAR(80) NOT NULL,

                        last_name VARCHAR(80) NOT NULL,

                        address VARCHAR(100) NOT NULL,

    -- Corrigido 'varhcar' para 'VARCHAR'.
                        gender VARCHAR(6) NOT NULL,

    -- Definindo a chave primária.
                        PRIMARY KEY (id)
);